# Generated by Django 3.2.25 on 2024-03-22 14:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('letsnote', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='note',
            name='title',
        ),
    ]
