# Generated by Django 3.2.25 on 2024-03-23 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('letsnote', '0002_remove_note_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='title',
            field=models.TextField(default='defaulttitle'),
            preserve_default=False,
        ),
    ]
