# Generated by Django 3.2.25 on 2024-03-24 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('letsnote', '0004_auto_20240324_2322'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='content',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='note',
            name='title',
            field=models.TextField(default='deftext'),
            preserve_default=False,
        ),
    ]
