# Generated by Django 3.2.25 on 2024-03-25 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('letsnote', '0005_auto_20240324_2323'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='created_date',
            field=models.TextField(default='2024-03-24'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='note',
            name='last_modified_date',
            field=models.TextField(default='2024-03-24'),
            preserve_default=False,
        ),
    ]
